### PR TITLE
V0.2.0 Pipeline build fails due to GDAL installation error

### PR DESCRIPTION
**Pull request by val-ismaili**
I'm attempting to release a v0.2.0 for Python 3.11 support. `Changelog.md` and `__init__.py` are straightfoward updates

Adding `python_requires='>=3.11'` into [`setup.py`](setup.py) requires the update of `python-version: 3.11` within the `build-pipeline.yml`

During the build process, the installation of GDAL via its wheel fails:

```
Installing collected packages: wheel
Successfully installed wheel-0.40.0
Collecting GDAL
  Downloading GDAL-3.6.3.tar.gz (757 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 757.9/757.9 kB 8.5 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: GDAL
  Building wheel for GDAL (setup.py): started
  Building wheel for GDAL (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [591 lines of output]
...
g++ -shared -Wl,--rpath=/opt/hostedtoolcache/Python/3.11.2/x64/lib -Wl,--rpath=/opt/hostedtoolcache/Python/3.11.2/x64/lib build/temp.linux-x86_64-cpython-311/extensions/gnm_wrap.o -L/opt/hostedtoolcache/Python/3.11.2/x64/lib -L/usr/lib -lgdal -o build/lib.linux-x86_64-cpython-311/osgeo/_gnm.cpython-311-x86_64-linux-gnu.so
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for GDAL
  Running setup.py clean for GDAL
Failed to build GDAL
```
so it then seems like an alternative method is attempted but also fails with the same error

```
Installing collected packages: GDAL
  Running setup.py install for GDAL: started
  Running setup.py install for GDAL: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Running setup.py install for GDAL did not run successfully.
  │ exit code: 1
  ╰─> [593 lines of output]
      WARNING: numpy not available!  Array support will not be enabled
      running install
      /opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
...
g++ -shared -Wl,--rpath=/opt/hostedtoolcache/Python/3.11.2/x64/lib -Wl,--rpath=/opt/hostedtoolcache/Python/3.11.2/x64/lib build/temp.linux-x86_64-cpython-311/extensions/gnm_wrap.o -L/opt/hostedtoolcache/Python/3.11.2/x64/lib -L/usr/lib -lgdal -o build/lib.linux-x86_64-cpython-311/osgeo/_gnm.cpython-311-x86_64-linux-gnu.so
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> GDAL

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
Error: Process completed with exit code 1.
```
See the full build log [here](https://github.com/arup-group/osmox/actions/runs/4572944507/jobs/8072776793)

To attempt a fix, in a previous commit (removed from here so the original issue is clear) I've tried adding `sudo apt-get install -y gcc` but pipeline outputs `gcc is already the newest version (4:11.2.0-1ubuntu1)` (see [commit](https://github.com/arup-group/osmox/commit/6f358e74ae53fcb4ae101f0c221a4825b588087b) and [build log](https://github.com/arup-group/osmox/actions/runs/4567256319/jobs/8060815391))

I've tried a bunch of different avenues as you can see in the all the commits below (😅) based on what I was able to find online but nothing seems to have worked so I've returned the commits back to the original state.

Any ideas of what's going on?

Summary:
- Able to build this state of osmox in a local Python 3.7 or 3.11 environment as per (https://github.com/arup-group/osmox/pull/35)
- Pinning a v0.1.0 to Python 3.7 in the build pipeline builds successfully (https://github.com/arup-group/osmox/compare/main...python3.7)
- For this commit - by adding a `python_requires>=3.11` then results in errors installing GDAL (even when GDAL is unpinned)
- Possible to just leave `python_requires>=3.7` which will allow the build pipeline to use 3.7 and users can install 3.11 locally. I assume this is just kicking the ball down the road though as at some point there might be a break in support?

### CODE REVIEW

**Review by mfitz — CHANGES_REQUESTED** [review]
I think you can now grab the latest `main` and merge it into this branch @val-ismaili. That will fix the build pipeline error. You will need to resolve conflicts in that file, but I think that will just be a case of accepting all of the changes from `main` and losing all of the ones you've made in this branch.

After that, you can return to the original purpose of this branch.

**Comment by val-ismaili** [comment]
@mfitz I've merged your changes from `main`. The CI builds successfully when specifying `python_requires='>=3.11'`in [setup.py](https://github.com/arup-group/osmox/pull/setup.py) and `python-version: 3.11` within the build-pipeline.yml but then fails on the AWS codebuild.

Changing to `python_requires='>=3.7'` and `python-version: 3.7` within build_pipeline.yml seems to work with the AWS codebuild. Any idea why AWS is affected by the 3.11 requirement?

Can leave it for now as current setup allows the user to install osmox on a 3.11 environment successfully.

**Comment by mfitz** [comment]
> Changing to `python_requires='>=3.7'` and `python-version: 3.7` within build_pipeline.yml seems to work with the AWS codebuild. Any idea why AWS is affected by the 3.11 requirement?

See the [Dockerfile](https://github.com/arup-group/osmox/blob/e83322163ca28c941bd1a00b46f798532778e17f/Dockerfile#L1) @val-ismaili

**Review by mfitz — CHANGES_REQUESTED** [review]
Looks good, but the changelog needs a minor tweak.

**Pull request merged**
