### PR TITLE
Allow infilling when target areas already have some required activities within them

### LINKED ISSUE #47: Infill in landuse areas that have existing facilities
### What can be improved?

When activity infilling, OSMOX currently ignores any landuse areas that contain facilities that have matching activities. There are cases when we want to infill because only a tiny proportion of a target area has facilities in it. Some ideas on how to do it:

1. Infill target areas that are already covered by < X% of a given activity type. E.g., if only 5% of the target area is already covered, then consider that area as requiring infilling.
2. Cut out the area taken up by existing facilities from a target area and infill only the new, smaller area. 

### Version

v0.2.0

### PR DESCRIPTION
**Pull request by brynpickering**
Fixes #47 

Focus is only on point 1 of #47.

Rather than set a binary flag to allow / disallow infilling in already occupied areas, I've made it a threshold fraction. This is based on percentage area occupied and has required me to expand any point activities to polygons. I chose to use the same sizing as would be used for infilling to approximate polygons for these points. Would be good to get an opinion on whether there is a better approach.

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator.
All others should be checked by the reviewer(s).
You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Tests added to cover contribution
- [ ] Documentation updated

### CODE REVIEW

**Comment by val-ismaili** [comment]
Yeah this is nice - a good way to limit how many areas will be affected. Though I think from a user perspective, you are more likely to be a bit more binary in your desire for infilling. A likely scenario for a study area might be that you have say the TE region, but want to infill a local area to real levels. An ability to point this method to a boundary file and say outside the study area use the method for just infilling completely empty areas, and then within the boundary infill all landuse up to the levels of the reference dataset (regardless of what % completion each area is in relation to the reference dataset)

**Comment by brynpickering** [comment]
This is independent of trying to meet a specific regional target and I think even if you had that target you wouldn't want to attempt to infill areas that already have 90% of the residential landuse filled with relevant activities, so a threshold for infilling would still be a good idea.

**Comment by val-ismaili** [comment]
> This is independent of trying to meet a specific regional target and I think even if you had that target you wouldn't want to attempt to infill areas that already have 90% of the residential landuse filled with relevant activities, so a threshold for infilling would still be a good idea.

Yeah I guess when enabling regional targets it would be useful to specify different thresholds for a study area vs outside study area.

**Comment by brynpickering** [comment]
Added similar images as in #46 .

**Pull request merged**
